### ISSUE TITLE
Sankey diagram

### ISSUE THREAD

**Issue by bganicky** [losomo/STVBallot#3]
Hi, I see some Sankey diagram related Perl scripts in the codebase. Is there a way to generate the Sankey diagram from voting results? Or is there at least some particular way to get to the diagram from voting results with external tools? Thanks for any advice!

**Comment by losomo** [comment]
Yes, call the script with json vote configuration as the first argument, and the textual protocol produced when counting the votes as the second argument.

**Comment by bganicky** [comment]
II was trying to make this work but haven't succeeded. I have the JSON file and the HTML protocol. Is the HTML protocol the right thing to provide as a second argument or is there yet another textual voting protocol format? When running `./tr2sankey.pl ballots.json protocol.html` it returns `Can't use an undefined value as a subroutine reference at ./tr2sankey.pl line 47, <$tr> line 1.` I was trying to debug a bit, but unfortunately I'm pretty unfamiliar with Perl. Thank you!

**Comment by losomo** [comment]
OK the input is not the HTML protocol, sorry about that.
1) Change false to true on line 6 of test.js
2) run `node test.js test_01.json 2> test_01.tr`
3) remove the last line with 'test_01.json OK' from test_01.tr
4) run `./tr2sankey.pl test_01.json test_01.tr`
It will complain about uninitialized values, but it will print out json data for a sankey diagram.

The tr file must have every line beginning with 'original', 'transferred', 'elected' or 'removed'. The error you mention will show up if that's not the case.

STVBallot supports votes with multiple STV rounds. Those can't be displayed in a sankey diagram, they will have lines starting with 'cycle start' and 'cycle end' and ./tr2sankey.pl will fail on those.
